# Generated by Django 4.2.5 on 2023-09-30 10:37
from ..models import Tier
from django.db import migrations, models
import django.utils.timezone

def create_predefined_tiers(apps, schema_editor):    
    Tier.objects.get_or_create(name='Basic', thumbnail_sizes='200', link_enabled=True, expiring_link_enabled=True)
    Tier.objects.get_or_create(name='Premium', thumbnail_sizes='200,400', link_enabled=True, expiring_link_enabled=True)
    Tier.objects.get_or_create(name='Enterprise', thumbnail_sizes='200,400', link_enabled=True, expiring_link_enabled=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('thumbnail_sizes', models.CharField(max_length=100, verbose_name='Thumbnail Sizes')),
                ('link_enabled', models.BooleanField(default=False, verbose_name='Link Enabled')),
                ('expiring_link_enabled', models.BooleanField(default=False, verbose_name='Expiring Link Enabled')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tier', models.ForeignKey(default=0, on_delete=models.SET(0), to='users.tier')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
          
        migrations.RunPython(create_predefined_tiers),
        
    ]
