# Generated by Django 4.2.5 on 2023-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='users.tier'),
        ),
    ]
